import type { SopLibraryItem } from "./data";

export const sopLibraryItems: SopLibraryItem[] = [
  {
    id: 'sop001',
    title: 'Pump Start/Stop Procedure',
    description: 'Standard procedure for safely starting and stopping a submersible pump.',
    category: 'Pumping',
    fileType: 'pdf',
    fileUrl: 'https://www.wsp.org/sites/wsp/files/publications/JMP-2017-final-launch-version.pdf',
    thumbnailUrl: 'https://picsum.photos/seed/sop1/400/300',
    tags: ['pump', 'start', 'stop', 'procedure'],
  },
  {
    id: 'sop002',
    title: 'How to Isolate a Pipeline Leak',
    description: 'A short video guide on identifying and isolating a leak in the main distribution line.',
    category: 'Pipeline',
    fileType: 'video',
    fileUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ', // Placeholder video
    thumbnailUrl: 'https://picsum.photos/seed/sop2/400/300',
    tags: ['leak', 'pipeline', 'repair', 'video'],
  },
  {
    id: 'sop003',
    title: 'Chlorination Steps for OHT',
    description: 'Detailed steps and dosage calculation for chlorinating an overhead tank.',
    category: 'Chlorination',
    fileType: 'image',
    fileUrl: 'https://picsum.photos/seed/sop3-full/800/1200',
    thumbnailUrl: 'https://picsum.photos/seed/sop3/400/300',
    tags: ['chlorine', 'tank', 'disinfection', 'oht'],
  },
  {
    id: 'sop004',
    title: 'Valve Operation Manual',
    description: 'Guide to operating different types of valves in the system.',
    category: 'General O&M',
    fileType: 'pdf',
    fileUrl: 'https://www.wsp.org/sites/wsp/files/publications/JMP-2017-final-launch-version.pdf',
    thumbnailUrl: 'https://picsum.photos/seed/sop4/400/300',
    tags: ['valve', 'operation', 'manual'],
  },
  {
    id: 'sop005',
    title: 'Daily Logbook Checklist',
    description: 'A checklist of all parameters to be recorded in the daily logbook.',
    category: 'General O&M',
    fileType: 'image',
    fileUrl: 'https://picsum.photos/seed/sop5-full/800/1200',
    thumbnailUrl: 'https://picsum.photos/seed/sop5/400/300',
    tags: ['logbook', 'checklist', 'daily'],
  },
  {
    id: 'sop006',
    title: 'Electrical Safety SOP',
    description: 'Crucial safety procedures to follow when working with electrical panels.',
    category: 'Safety',
    fileType: 'pdf',
    fileUrl: 'https://www.wsp.org/sites/wsp/files/publications/JMP-2017-final-launch-version.pdf',
    thumbnailUrl: 'https://picsum.photos/seed/sop6/400/300',
    tags: ['safety', 'electrical', 'panel', 'sop'],
  },
];
